# Generated by Django 4.1.5 on 2023-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_active_userinfo_allow_friend_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password_reset_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
