# Generated by Django 4.1.5 on 2023-02-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='display_active',
            field=models.BooleanField(default=True),
        ),
    ]
