# Generated by Django 4.1.5 on 2023-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_display_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_email',
            field=models.BooleanField(default=False),
        ),
    ]
