# Generated by Django 4.1.5 on 2023-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_friend_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dispaly_dob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
