# Generated by Django 4.1.5 on 2023-02-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_allow_friend_request_user_allow_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dispaly_dob',
            new_name='display_dob',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
